[build]
  publish = "."
  command = ""

[[headers]]
  for = "/app-ads.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 